title: Satya Pati
description: My Personal Website
author: Satya Pati
logo: satyalytics.github.io/static/img/dp.png
github: https://github.com/satyalytics
about: Somewhere in Data

baseurl: "https://satyalytics.github.io/"
url: "/satyalytics"

allowsearch: true

disqus_shortname: satya
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]