title: Satya Pati
description: My Personal Webpage
author: Satya Pati
logo: /static/img/dp.png
github: https://github.com/satyalytics
about: Somewhere in data

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: talk_satya
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 10
per_page: 10
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
